version: '3.4'

services:
   catalogdb:
       image: mongo
   basketdb:
       image: redis
   orderdb:
       image: postgres
       environment:
        POSTGRES_PASSWORD: 0000
   rabbitmq:
       image: rabbitmq:3-management-alpine
   catalog.api:
       image: ${DOCKER_REGISTRY-}catalogapi
       build:
           context: .
           dockerfile: src/Catalog/Catalog.API/Dockerfile
   basket.api:
       image: ${DOCKER_REGISTRY-}basketapi
       build:
           context: .
           dockerfile: src/Basket/Basket.API/Dockerfile
   ordering.api:
       image: ${DOCKER_REGISTRY-}orderingapi
       depends_on: 
            - rabbitmq
       build:
           context: .
           dockerfile: src/Ordering/Ordering.API/Dockerfile
   apigateway:
       image: ${DOCKER_REGISTRY-}apigateway
       build:
           context: .
           dockerfile: src/OcelotApiGateway/Dockerfile
   shoppingweb:
       image: ${DOCKER_REGISTRY-}shoppingweb
       build:
           context: .
           dockerfile: src/ShoppingWeb/Dockerfile